### ISSUE TITLE
Users would like the ability to delete a submitted spatial file

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr_fsa2#41]
Each submitted spatial file overwrites the last for a specific submission type - i.e.: Cut Block submission 2 overwrites cut block submission 1. However, if the client accidentally submits a road file instead of an intended cut block file, there is no way to delete that road submission. 

Users would like the ability to delete a submitted spatial file.

Business would like to list submissions made on the upload screen with a trash can icon or some method of deletion beside each

**This issue transferred from Jira (FOM-112)**

![screenshot-1.png](https://images.zenhubusercontent.com/61f87aa78804f87afc5530bd/2f21c29e-1921-45b9-a847-c4d60f09af4c)

**Comment by basilv** [comment]
This was in progress and work will be completed in JIRA. Closing this.

**Comment by basilv** [comment]
Hmm, looks like I can't actually close issues here in GitHub, only comment?

**Comment by DerekRoberts** [comment]
@basilv How about now?  Access has been stepped up.
