### ISSUE TITLE
relabel Irrelevant Comments on Summary screen

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr_fsa2#43]
On the summary screen, relabel "Irrelevant Comments" to Non Applicable Comments

**Issue transferred from Jira (FOM-113)**

**Comment by basilv** [comment]
FYI we are actively working on these JIRA, it probably doesn't make sense to transfer ones in progress. Or we need a discussion on  transitioning to GitHub issues. It can be a short discussion, just need to have a shared understanding of what we are doing.

**Comment by gormless87** [comment]
I wasn't sure about the in progress issues and certainly do not want to complicate things or add work. I will discuss with the team and get back to you.

**Comment by gormless87** [comment]
This issue was in-progress when copied from Jira (FOM-113). Work will be recorded in Jira, closing FOM backlog items issue.
